### ISSUE TITLE
SNA/Join command crash

### ISSUE THREAD

**Issue by mini** [Weeby-Feet/AkashBot#3]
Bot crashes if user not in voice channel, add a check

https://github.com/Weeby-Feet/AkashBot/blob/1ac2f3f99fdef22624049dbda15616cb1334a0cc/index.js#L38-L40

https://github.com/Weeby-Feet/AkashBot/blob/1ac2f3f99fdef22624049dbda15616cb1334a0cc/index.js#L47-L51

**Comment by Weeby-Feet** [comment]
Added a check to make sure that the user that summoned the bot is actually in a voice channel.
