### ISSUE TITLE
Help command crash

### ISSUE THREAD

**Issue by mini** [Weeby-Feet/AkashBot#4]
Bot processes its own replies. So when it sends help text to user's private message channel, it clearly won't have a guild.

https://github.com/Weeby-Feet/AkashBot/blob/1ac2f3f99fdef22624049dbda15616cb1334a0cc/index.js#L18-L21

**Comment by Weeby-Feet** [comment]
Bot no longer reads their own replies and no longer crashes when you send it commands via direct message.
